sonar.projectKey=vzakharchenko_Forge-Secure-Notes-for-Jira
sonar.organization=vzakharchenko

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=test/**,static/**,__tests__/**,example-app-integration/**,trust-logic/**,web-site/**, src/database/migration/**
sonar.cpd.exclusions=static/**,__tests__/**,web-site/***, src/database/migration/**

sonar.issue.ignore.multicriteria=e1,e2

sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S7786
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*

sonar.issue.ignore.multicriteria.e2.ruleKey=typescript:S7781
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*