export const FORGE_INJECTION_TOKENS = {
  AnalyticService: Symbol.for("AnalyticService"),
  BootstrapService: Symbol.for("BootstrapService"),
  ContextService: Symbol.for("ContextService"),
  KVSSchemaMigrationService: Symbol.for("KVSSchemaMigrationService"),
  RovoServiceImpl: Symbol.for("RovoServiceImpl"),
  SecurityNoteService: Symbol.for("SecurityNoteService"),
  AuditUserController: Symbol.for("AuditUserController"),
  AuditUsersController: Symbol.for("AuditUsersController"),
  BootStrapController: Symbol.for("BootStrapController"),
  FetchSecurityNoteController: Symbol.for("FetchSecurityNoteController"),
  IssueAuditController: Symbol.for("IssueAuditController"),
  IssueProjectsController: Symbol.for("IssueProjectsController"),
  OpenSecurityNoteController: Symbol.for("OpenSecurityNoteController"),
  ProjectAuditController: Symbol.for("ProjectAuditController"),
  CreateSecurityNoteController: Symbol.for("CreateSecurityNoteController"),
  DeleteSecurityNoteController: Symbol.for("DeleteSecurityNoteController"),
  GetMySecurityNotesController: Symbol.for("GetMySecurityNotesController"),
  ApplySchemaMigrationTrigger: Symbol.for("ApplySchemaMigrationTrigger"),
  DropSchemaMigrationTrigger: Symbol.for("DropSchemaMigrationTrigger"),
  FiveMinutesTrigger: Symbol.for("FiveMinutesTrigger"),
  SlowQueryTriggerTrigger: Symbol.for("SlowQueryTriggerTrigger"),
  SecurityNoteRepository: Symbol.for("SecurityNoteRepository"),
  SecurityStorage: Symbol.for("SecurityStorage"),
  JiraUserService: Symbol.for("JiraUserService"),
  AsyncService: Symbol.for("AsyncService"),
};
