/**
 * This file was auto-generated by forge-sql-orm
 * Generated at: 2025-05-24T07:59:51.770Z
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Any changes will be overwritten on next generation
 */
 
 
export * from "./relations";
export * from "./schema";

export interface VersionFieldMetadata {
  fieldName: string;
}

export interface TableMetadata {
  tableName: string;
  versionField: VersionFieldMetadata;
}

export type AdditionalMetadata = Record<string, TableMetadata>;

export const additionalMetadata: AdditionalMetadata = {};
